export const COLLECTOR_LEVELS = [
  {
    min: 0,
    max: 2,
    label: 'Novato',
    color: 'text-zinc-500',
    bg: 'bg-zinc-100 dark:bg-zinc-800',
    border: 'border-zinc-300 dark:border-zinc-600',
    icon: '🌱',
  },
  {
    min: 3,
    max: 9,
    label: 'Coleccionista',
    color: 'text-emerald-600',
    bg: 'bg-emerald-50 dark:bg-emerald-950/40',
    border: 'border-emerald-300 dark:border-emerald-700',
    icon: '🃏',
  },
  {
    min: 10,
    max: 24,
    label: 'Cazador',
    color: 'text-blue-600',
    bg: 'bg-blue-50 dark:bg-blue-950/40',
    border: 'border-blue-300 dark:border-blue-700',
    icon: '🎯',
  },
  {
    min: 25,
    max: 49,
    label: 'Maestro',
    color: 'text-primary',
    bg: 'bg-primary/10 dark:bg-primary/20',
    border: 'border-primary/30 dark:border-primary/50',
    icon: '⚔️',
  },
  {
    min: 50,
    max: Infinity,
    label: 'Legendario',
    color: 'text-amber-600',
    bg: 'bg-amber-50 dark:bg-amber-950/40',
    border: 'border-amber-300 dark:border-amber-700',
    icon: '👑',
  },
] as const;
