











/** Maps category IDs to their dedicated URL path segment (non-singles categories). */
export const CATEGORY_TO_PATH: Record<string, string> = {
  Bundle: 'bundles',
  PRECON_DECK: 'decks',
  MICAS: 'micas',
};

/** Reverse map: URL path segment → category ID, for active-state detection. */
export const PATH_TO_CATEGORY: Record<string, string> = {
  singles: 'singles',
  bundles: 'Bundle',
  decks: 'PRECON_DECK',
  micas: 'MICAS',
};

export const CATEGORY_NAME_MAP: Record<string, string> = {
  SINGLES: 'singles',
  BUNDLE: 'Bundle',
  PRECON_DECK: 'PRECON_DECK',
  POKEMON: 'pokemon',
  MTG: 'mtg',
  YUGIOH: 'yugioh',
  SPORTS: 'sports',
  MARVEL: 'marvel',
  ONE_PIECE: 'one-piece',
  DIGIMON: 'digimon',
  VANGUARD: 'vanguard',
  FLESH_AND_BLOOD: 'flesh-and-blood',
  HEROClix: 'heroclix',
  KEYFORGE: 'keyforge',
  STAR_WARS: 'star-wars',
  LORC: 'lorc',
  WIZARDS: 'wizards',
  DRAGON_BALL_SUPER: 'dragon-ball-super',
  DRAGON_BALL_Z: 'dragon-ball-z',
  NARUTO: 'naruto',
  BLEACH: 'bleach',
  ONE_PUNCH_MAN: 'one-punch-man',
  MY_HERO_ACADEMIA: 'my-hero-academia',
  FORTNITE: 'fortnite',
  CALL_OF_DUTY: 'call-of-duty',
  OVERWATCH: 'overwatch',
  LEAGUE_OF_LEGENDS: 'league-of-legends',
  VALORANT: 'valorant',
  CS_GO: 'cs-go',
  DOTA_2: 'dota-2',
  TEAM_FORTRESS_2: 'team-fortress-2',
  APEX_LEGENDS: 'apex-legends',
  RAINBOW_SIX: 'rainbow-six',
  FIFA: 'fifa',
  NBA_2K: 'nba-2k',
  MADDEN_NFL: 'madden-nfl',
  NHL: 'nhl',
  MLB_THE_SHOW: 'mlb-the-show',
  WWE_2K: 'wwe-2k',
  UFC: 'ufc',
  GRAN_TURISMO: 'gran-turismo',
  MICAS: 'MICAS',
  MONOPOLY: 'monopoly',
  SETTLERS_OF_CATAN: 'settlers-of-catan',
  DUNGEONS_AND_DRAGONS: 'dungeons-and-dragons',
  PATHFINDER: 'pathfinder',
  WARHAMMER: 'warhammer',
  MAGIC_THE_GATHERING: 'magic-the-gathering',
  POKEMON_TCG: 'pokemon-tcg',
  YU_GI_OH: 'yu-gi-oh',
  CARDFIGHT_VANGUARD: 'cardfight-vanguard',
  LEGENDS_OF_RUNETERRA: 'legends-of-runeterra',
  HEARTHSTONE: 'hearthstone',
  Gwent: 'gwent',
  ARTIFACT: 'artifact',
  STAR_WARS_UNLIMITED: 'star-wars-unlimited',
  SCARLET_WITCH: 'scarlet-witch',
  DESTINY_2: 'destiny-2',
  FORTNITE_SAVE_THE_WORLD: 'fortnite-save-the-world',
  ROCKET_LEAGUE: 'rocket-league',
  FALL_GUYS: 'fall-guys',
  MINECRAFT: 'minecraft',
  TERRARIA: 'terraria',
  STARDEW_VALLEY: 'stardew-valley',
  ANIMAL_CROSSING: 'animal-crossing',
  ZELDA: 'zelda',
  SUPER_MARIO: 'super-mario',
  MARIO_KART: 'mario-kart',
  SONIC: 'sonic',
  CRASH_BANDICOOT_NITRAC: 'crash-bandicoot-nitrac',
  SPYRO_THE_DRAGON: 'spyro-the-dragon',
  RAYMAN: 'rayman',
  METAL_GEAR_SOLID: 'metal-gear-solid',
  DARK_SOULS: 'dark-souls',
  BLOODBORNE: 'bloodborne',
  SEKIRO: 'sekiro',
  ELDEN_RING: 'elden-ring',
  HORIZON_ZERO_DAWN: 'horizon-zero-dawn',
  FORZA_HORIZON_5: 'forza-horizon-5',
  GRAN_TURISMO_7: 'gran-turismo-7',
  ASSASSINS_CREED_VALHALLA: 'assassins-creed-valhalla',
  WATCH_DOGS_LEGION: 'watch-dogs-legion',
  FAR_CRY_6: 'far-cry-6',
  CYBERPUNK_2077: 'cyberpunk-2077',
  RED_DEAD_REDEMPTION_2: 'red-dead-redemption-2',
  GOD_OF_WAR: 'god-of-war',
  SPIDER_MAN: 'spider-man',
  MARVELS_SPIDER_MAN_MILES_MORALES: 'marvels-spider-man-miles-morales',
  BATMAN_ARKHAM_KNIGHT: 'batman-arkham-knight',
  JUSTICE_LEAGUE: 'justice-league',
  INJUSTICE: 'injustice',
  MORTAL_KOMBAT_11: 'mortal-kombat-11',
  TEKKEN_8: 'tekken-8',
  STREET_FIGHTER_6: 'street-fighter-6',
  SOULCALIBUR_6: 'soulcalibur-6',
};
