services:
  hydra-admin-app:
    build:
      context: ./app
      dockerfile: Dockerfile
    container_name: hydra-admin-app
    ports:
      - "3001:3001"
    env_file:
      - .env
    depends_on:
      - hydra-admin-api
      - redis
    restart: unless-stopped
    networks:
      - hydra-network

  hydra-admin-api:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: hydra-admin-api
    ports:
      - "3002"
    env_file:
      - .env
    environment:
      - PORT=3002
      - REDIS_URL=redis://redis:6379
    depends_on:
      redis:
        condition: service_started
    restart: unless-stopped
    networks:
      - hydra-network

  redis:
    image: redis:7-alpine
    container_name: hydra-admin-redis
    ports:
      - "6379:6379"
    restart: unless-stopped
    volumes:
      - redis-data:/data
    networks:
      - hydra-network

volumes:
  redis-data:

networks:
  hydra-network:
    driver: bridge
