// This file was generated by Prisma and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import 'dotenv/config';
import { defineConfig } from 'prisma/config';

// During `prisma generate` (build time) no real DB is needed — use placeholder.
// During `prisma migrate deploy` (runtime) DATABASE_URL must be set.
const databaseUrl = process.env.DATABASE_URL ?? 'postgresql://localhost/placeholder';
// directUrl is the non-pooled connection required by Supabase for migrations.
const directUrl = process.env.DIRECT_URL ?? databaseUrl;

export default defineConfig({
  schema: 'prisma/schema.prisma',
  migrations: {
    path: 'prisma/migrations',
  },
  datasource: {
    url: databaseUrl,
    directUrl,
  },
});
